#!/usr/bin/env node
/**
 * Give the built Worker a `scheduled()` handler.
 *
 * Cloudflare Cron Triggers invoke `scheduled()`. The Astro Cloudflare adapter
 * emits an entrypoint that exports `fetch` and nothing else, so without this
 * there is no way to run anything on a schedule — which is why payment
 * reminders only ever went out when somebody remembered to press the button.
 *
 * Rather than build a second Worker with its own half-wired copy of the app,
 * the generated handler calls straight back into the app's own `fetch` with
 * an internal request. The job then runs inside the real application, with
 * every binding, every helper and the ordinary middleware already in place.
 *
 * Run after `astro build`. It rewrites dist/server/wrangler.json to point at
 * the wrapper instead of the adapter's entry.
 */

import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const SERVER_DIR = join(process.cwd(), 'dist', 'server');
const CONFIG = join(SERVER_DIR, 'wrangler.json');
const WRAPPER = 'worker-with-cron.mjs';

/** Which cron expression runs which task. Must match wrangler.jsonc. */
const SCHEDULE = {
  '0 8 * * *': 'reminders',
  '0 3 * * 0': 'housekeeping',
};

const wrapper = `// GENERATED by scripts/wrap-worker.mjs — do not edit.
//
// Wraps the Astro adapter's entrypoint so the Worker has a scheduled()
// handler as well as fetch(). See the script for why.
import app from './entry.mjs';

const SCHEDULE = ${JSON.stringify(SCHEDULE, null, 2)};

export default {
  fetch: app.fetch,

  async scheduled(event, env, ctx) {
    const task = SCHEDULE[event.cron] ?? 'reminders';
    const base = env.APP_URL || 'https://billing.jwbsstudio.com';

    if (!env.CRON_SECRET) {
      console.log(
        '[cron] ' +
          JSON.stringify({
            cron: event.cron,
            task,
            skipped: 'CRON_SECRET is not set, so scheduled work is disabled.',
          }),
      );
      return;
    }

    const request = new Request(new URL('/api/cron/' + task, base), {
      method: 'POST',
      headers: {
        authorization: 'Bearer ' + env.CRON_SECRET,
        // The middleware rejects a cross-origin state-changing request. This
        // one originates inside the Worker, so it names the app's own origin.
        origin: new URL(base).origin,
      },
    });

    const run = (async () => {
      try {
        const response = await app.fetch(request, env, ctx);
        const body = await response.text();
        console.log(
          '[cron] ' +
            JSON.stringify({ cron: event.cron, task, status: response.status, body: body.slice(0, 2000) }),
        );
      } catch (error) {
        console.log('[cron] ' + JSON.stringify({ cron: event.cron, task, error: String(error) }));
      }
    })();

    // Keep the Worker alive until the sweep finishes; a scheduled invocation
    // is torn down the moment the handler returns otherwise.
    ctx.waitUntil(run);
    await run;
  },
};
`;

const config = JSON.parse(await readFile(CONFIG, 'utf8'));

if (config.main !== 'entry.mjs' && config.main !== WRAPPER) {
  throw new Error(
    `Expected the adapter to emit main: "entry.mjs", got "${config.main}". ` +
      'The adapter has changed shape — check scripts/wrap-worker.mjs before deploying.',
  );
}

await writeFile(join(SERVER_DIR, WRAPPER), wrapper, 'utf8');
config.main = WRAPPER;
await writeFile(CONFIG, JSON.stringify(config, null, 2), 'utf8');

console.log(`[wrap-worker] scheduled() added; main -> ${WRAPPER}`);
